# Semantic routing - for intelligently routing user queries to the right handler
from semantic_router import Route, SemanticRouter
from semantic_router.encoders import HuggingFaceEncoder

# Initialize the encoder that will convert text into numerical vectors for similarity matching
encoder = HuggingFaceEncoder(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Define the "appointment" route - handles all queries related to booking, checking, or managing appointments
# This includes doctor availability, scheduling, rescheduling, and cancellation requests
appointment = Route(
    name="appointment",  # Route identifier
    utterances = [  # Sample phrases that should trigger this route
    "Did my appointment go through?", "I need to change my appointment time.", 
    "I want to fix an appointment.", "Can I book appointments online or through the app?", 
    "How do I book an appointment with a doctor?", "How do I reschedule or cancel my appointment?", 
    "What is the procedure to book an appointment?", "Is online booking available?", 
    "Can I use the app to book?", "Cancel my booking for tomorrow.", "Check my booking status." 
    'which doctor are available today?', 'which doctor are available today with there specialties?',
    'list all the doctors available today?','show me all the doctors available today?',
    'do you have any doctors available today?', 'list the doctors available today along with there specialization?',
    'give me the list of doctors available today with there specialization?', 'show me the list of doctors available today with there specialization?',
    'which doctors are free today?', 'list all the specialists available today?',
    'when is Dr. Natasha Verma available', 'what is the availability of Dr. Raghav Menon',
    'show me the availability of Dr. Ananya Kulkarni', 'give me the availability timings of Dr. Arvind Bhatia',
    'at what time is Dr. Sneha Patwardhan available', 'what are the timings for Dr. Karan Das',
    'show me the timings for Dr. Priya Venkatesh','when does Dr. Naveen Saini see patients',
    'what is the OPD time of Dr. Ritu Kohli', 'show me the availability of Dr. Ajay Rawat', 
    'which doctors are there today?', 'list all the doctors today?', 'show me all the doctors today?',
    'which doctors are there?', 'which is the doctor for heart', 'which is the doctor for bones',
    'who is the neurologist', 'is there a dermatologist available', 'when can I meet a gynecologist',
    'which specialist should I visit for back pain',
    "Show me all doctors", "List all doctors", "Which doctors are available", "Show doctor names",
    "List doctors by specialization", "Who are the cardiologists", "Show neurologists",
    "Which doctors specialize in orthopedics", "Find a doctor by specialization", "Show doctor details",
    "Tell me about doctors", "Which doctors work here", "When is the doctor available", "Doctor availability today",
    "Which doctors are available today", "Check doctor availability", "Show available time slots",
    "Doctor schedule for today", "Doctor availability on Monday", "Is doctor available tomorrow",
    "What time is the doctor available", "Show doctor working hours", "Which doctors are available now", "Doctor availability this week",
    "Book an appointment", "I want to book a doctor appointment", "Schedule an appointment",
    "Fix an appointment with doctor", "Book appointment for today", "Book appointment for tomorrow",
    "I need to see a doctor", "Schedule visit with doctor", "Book appointment for patient",  "Create a new appointment",
    "Register my appointment", "Check my appointment", "Show my appointment details", "Do I have an appointment",
    "Find my appointment", "Appointment status", "Check appointment status", "View my appointment", "Show appointment information",
    "Get appointment details", "Is my appointment confirmed", "Reschedule my appointment", "Change my appointment time",
    "Update appointment date",  "Move my appointment", "Postpone my appointment", "Change appointment timing", "Modify my appointment",
    "Shift my appointment", "Update doctor appointment", "Cancel my appointment", "Delete my appointment", "I want to cancel appointment",
    "Remove my booking", "Cancel doctor visit", "Cancel scheduled appointment", "Drop my appointment", "Abort my appointment",
    "Show appointments for patient", "Find appointment by patient name",  "Patient appointment details",
    "List my appointments", "Show my doctor appointments", "My appointment history", "Upcoming appointments for me"
    "I want to book an appointment with a doctor.",  "How do I schedule a consultation?", "Can you help me fix a meeting with a specialist?",
    "What is the process to book a doctor visit?", "Are there any appointment slots available today?", "I need to check appointment availability.", 
    "Can I get an appointment for tomorrow?", "How soon can I get a consultation?", "Is online appointment booking available?", "Help me arrange an appointment with a physician.",
    "When is this doctor available?", "Show me the availability of Dr. Raghav.", "Does Dr. Priya have OPD hours today?", "Which days can I meet the cardiologist?",
    "What time does the dermatologist see patients?", "Check availability for Dr. Swati.", "Is any doctor available on Sunday?", "Show me today's available doctors.",
    "What are the timings for Dr. Mohit?", "Tell me which doctors are free right now.","I need a list of cardiologists.",
    "Who are the orthopedic doctors here?", "Do you have any neurologists?", "Find doctors specializing in pediatrics.",
    "Show me all dermatologists.", "Which doctor treats kidney issues?",  "Who handles reproductive medicine cases?",
    "Give me the available gastroenterologists.", "Find ENT specialists for consultation.",  "Which specialist should I visit for back pain?",
    "What is the OPD schedule for Dr. Neha?", "Show me OPD timings for pediatricians.", "When is the next OPD for dermatology?", "Which days does Dr. Gautam run OPD?",
    "Give me OPD hours for the spine surgeon.", "Tell me the OPD timing for Monday.", "Does any doctor have OPD during evening hours?",
    "When is OPD open on weekends?", "Show all OPD schedules for this week.", "What are the OPD hours for foreign doctors?", "Which doctors are available today?",
    "Show me all the doctors.", "List all the specialists.", "Which cardiologist is available?",  "Do you have any Indian doctors?",
    "Which doctors are from the USA?",  "Who is the neurologist here?", "Is there a dermatologist available right now?", "When can I meet a gynecologist?",
    "Show me orthopedic surgeons.", "Who is available on Monday?", "Which doctor works on Tuesday?", "Do you have any OPD on Wednesday?",
    "Which doctors see patients on Thursday?", "Who is available on Friday?", "Do any doctors work on Saturday?", "Is there OPD on Sunday?",
    "Which doctor has Sunday availability?", "Show doctor timings for Monday.", "Show doctor timings for Saturday.",
    "At what time is Dr. Raghav Menon available?", "When does Dr. Ananya Kulkarni start OPD?",  "What is Dr. Arvind Bhatia's availability?",
    "What are the timings for Dr. Sneha Patwardhan?", "At what time can I meet Dr. Karan Das?", "Show timing for Dr. Priya Venkatesh.", "When does Dr. Naveen Saini see patients?",
    "Timing for Dr. Ritu Kohli please.", "What is the OPD time of Dr. Ajay Rawat?",  "Show availability of Dr. Swati Mishra.", "Which doctor is available between 9 and 11 AM?",
    "Any doctor available after 2 PM?", "Show morning OPD sessions.", "Show afternoon doctor timings.", "Which doctor is available for 3 hours?",
    "Show doctors with 2 hour OPD.", "Do any doctors have evening slots?", "Show doctors with slots before noon.", "Which doctor works with longest duration?",
    "Who has a short OPD duration?", "Can I book an appointment?", "I want to schedule a consultation.", "Find me a free slot.", "Which doctor can I meet right now?",
    "Are any doctors available today?", "Show available slots today.",  "Find earliest available appointment.",  "Next available doctor please.",
    "Show all appointment options.", "Who is free right now?", "What specialization does Dr. Rohan Iyer have?",  "Give me doctor specialization details.",
    "Which doctors are nephrologists?", "Do you have an ENT specialist?", "List hematologists available.",  "I need a physiotherapist timing.",
    "Is there a urologist available?",  "Show radiologist OPD timing.", "Any gastroenterologists available?",  "Which doctors are rheumatologists?",
    "What nationality is Dr. Emily Carter?",  "Show nationality for each doctor.", "List foreign doctors.", "Which doctors are from Japan?", "Is there an Egyptian doctor?",
    "Which Indian doctors are available today?", "Show all Indian specialists.", "List doctors by nationality.", "Who is the US doctor?", "Show European doctors.",
    "Show full weekly schedule for all doctors.",  "Give me the weekly availability chart.", "I want the schedule for the whole week.",
    "Which days does Dr. Mohit Jain work?", "Does Dr. Tanya Sood work on weekends?", "Is there any Thursday OPD?", "Friday OPD list please.",
    "Saturday schedule for all doctors.", "Sunday schedule for available doctors.", "Do any doctors have two-day OPD?", "Do you have a doctor available before 10 AM?",
    "Do you have OPD after 5 PM?", "Is there any OPD at 8 AM?", "Can I meet a doctor at noon?", "Show timings earlier than 11 AM.",  "Show timings later than 3 PM.",
    "Find OPDs longer than 2 hours.", "Are there back-to-back OPD sessions?",  "Longest OPD duration today?", "Shortest OPD session today?",
    "Which OPD is available on Monday morning?", "Which doctor has Wednesday afternoon?", "What OPDs are available Tuesday evening?", "Show all OPDs for Thursday.",
    "List all Friday availability.", "Is there a Sunday morning OPD?", "Which doctors work two shifts?", "Find overlapping OPD timings.",
    "Which doctors have similar slots?",  "Compare timings for cardiologist and neurologist.",  "Show availability for cardiologist this week.",
    "I want to meet an endocrinologist.",  "Any pulmonologist available tomorrow?",  "Where is the pediatrician's schedule?",  "When can I meet a psychiatrist?",
    "Show hepatologist availability.",  "Find spine surgeon timing.", "Reproductive specialist availability please.", "Endoscopic surgeon OPD timings.",
    "Infectious disease specialist availability.", "When is OPD for cardiology?", "Show dermatology OPD schedule.",  "When does neurology OPD start?",
    "Gynecology OPD timings?", "Orthopedic OPD time?", "Endocrinology OPD days?", "General medicine OPD details.", "Psychiatry OPD schedule.", "Pulmonology OPD today?",
    "Pediatrics OPD time?", "Which doctor is free tomorrow?", "Next day schedule please.", "Show tomorrow OPD timings.", "Which doctor works tomorrow morning?",
    "Available specialists tomorrow?", "Any early morning OPD tomorrow?", "Tomorrow evening OPD?", "Doctors with morning shift tomorrow.",  "Tomorrow afternoon availability.",
    "Tomorrow full schedule.", "I want an appointment for Monday.", "Is Tuesday morning available?", "Can I meet a doctor Wednesday afternoon?", "Is Thursday OPD open?",
    "Book me a slot for Friday.",  "Saturday appointments available?", "Is Sunday OPD running?", "Next Monday schedule please.", "Next Wednesday doctor list.",
    "Weekend availability please.", "Do any doctors work multiple days?", "Which doctor works the most days?", "Who works only one day?",
    "Show doctors with weekend duties.", "Show weekday doctors.", "Who has the longest OPD on any day?", "Which doctor has shortest OPD window?", "Doctors with evening shifts.",
    "Doctors with morning-only shifts.", "Doctors with mid-day sessions.", "Find all OPDs between 10 AM and 2 PM.", "Show doctors whose timings overlap.",
    "Slot clash detection please.", "Which doctors have identical timings?", "Find all doctors available at 9 AM.", "Any doctor available after 4 PM?",
    "Who is available at 3 PM?", "Show appointments for time 11 AM.", "Doctor availability at 1 PM.", "Check availability at 6 PM.",
    "Show OPD on Monday and Thursday.", "Which doctors work both Friday and Saturday?", "Who has two OPDs in a week?", "Doctors with a Sunday shift.",
    "Doctors available more than once a week.", "Doctors working only on weekends.", "Doctors with mixed weekday-weekend schedule.",
    "List multi-day availability doctors.", "Show day combinations for doctors.", "Doctor working alternate days?", "I want a doctor with a short wait time.",
    "Find a doctor available soon.", "Earliest available doctor please.", "Doctor with least busy schedule.", "Show doctors with quick consultation windows.",
    "Which doctor has earliest start time?", "Which doctor finishes last?", "Doctor with longest OPD duration.",  "Doctor with fixed OPD pattern.",
    "Show all OPD durations.", "Give me the complete doctor list.", "Export all doctor timings.", "Show database info.", "How many doctors do you have?",
    "Count all doctors by specialization.","Show number of OPDs per doctor.","Sort doctors by start time.", "Sort doctors by duration.", "Sort doctors by nationality.",
    "Can I filter doctors by specialization?", "Filter doctors by nationality.", "Filter by day of week.", "Filter by time range.", "Find only Indian specialists.",
    "Find only foreign specialists.", "Show specialists available today.", "Give me OPDs for each specialization.", "Which specializations are available today?",
    "Specialization-wise availability please." "I need a doctor.", "Can I see a specialist today?",  "How do I get a token for a consultation?",  "Will I get a text after I book?",
    "What should I bring for my checkup?",    "Will I receive a confirmation message after booking?",
    "What documents should I bring for consultation?", "How early should I arrive before my appointment?",
    "Can I choose a specific doctor or specialist?", "Do I need a referral to see a specialist?",
    "How long is the average waiting time?",    "I want to complain about something.", "How do I give feedback?", "Do I need my ID for the doctor?", "Should I bring my old files?",
    "How early should I come?", "Do I need to be there 15 minutes before?", "What's the check-in process?",
    "I want to see a specific cardiologist.", "Can I pick my own doctor?", "Who is the best neurologist there?",
    "Do I need a letter from my local GP?", "Is a referral mandatory?", "Can I just walk in without a referral?",
    "How long is the queue?", "Is there a long wait today?", "When will the doctor see me?",
"Can doctors prescribe medicines online?", "Are teleconsultations covered by insurance?",
    "The call got disconnected, what do I do?", "Reconnect me to my doctor.",
])

# Define the "faq" route - handles general hospital information, services, and policies
# This includes hospital timings, locations, insurance, billing, emergency services, and facilities
faq = Route(
    name="faq",  # Route identifier
    utterances = [  # Sample phrases that should trigger this route
    "What services does Apollo Hospital provide?", "What are the hospital's working hours?", "specific timing for visiting patient?", 
    "How can I contact Apollo Hospital customer care?",  "Does Apollo Hospital offer emergency services 24/7?",
    "How do I locate the nearest Apollo Hospital branch?", "what are the timing for relative to visit paitent",
    "Are visitors allowed inside patient wards?", "What are the hospital's visitor timings?",
    "Does Apollo Hospital have pharmacy and diagnostic centers on-site?", "How can I provide feedback or file a complaint?",
    "Can international patients book virtual consultations?",
    "Does Apollo Hospital accept health insurance?", "Which insurance providers are empanelled?",
    "How do I claim insurance for treatment?", "Do I need pre-authorization for cashless treatment?",
    "What payment modes are accepted?", "Will I get a detailed bill breakdown?",
    "Are consultation charges refundable?","Is EMI available for surgeries?",
    "How do I get a duplicate invoice?",  "Are diagnostic tests covered under insurance?",
    "How can I access my medical reports online?", "How long does it take for diagnostic reports?",
    "Can I download my prescriptions digitally?", "How do I update my patient details?",
    "Can I request old medical records?", "How secure is my medical data?",
    "Can someone else collect my report?", "How long are records stored?",
    "How do I share my reports with another doctor?", "Can I get a second opinion?",
    "What should I do in an emergency?", "Does Apollo provide ambulance services?",
    "How do I call for an ambulance?", "What services are available in emergency rooms?",
    "Do I need an appointment for emergency care?", "Are emergency treatments covered by insurance?",
    "Does Apollo have trauma care units?", "What is the triage process?",
    "Are ICU beds available 24/7?", "Can relatives stay in critical care areas?",
    "What is the process for admission?",
    "What documents are required?", "How are room charges calculated?",
    "What room categories are available?", "Can I choose my room type?",
    "What is included in room charges?", "How do I prepare for surgery?",
    "Can I meet the anesthesiologist before surgery?",
    "How long is hospital stay after surgery?", "Can attendants stay with the patient?",
    "Does Apollo offer teleconsultation?", "How do I book teleconsultation?",
    "What equipment do I need?", "Can I upload reports before the appointment?",
    "How do I access the Apollo 24/7 app?", "Can I chat with medical support?",
    "Can I track prescriptions online?", "What if my video call disconnects?",
    "How do I book a lab test?", "Do I need a prescription?",
    "When are blood test results available?", "What fasting is required?",
    "Is home sample collection available?", "What imaging services are available?",
    "Is contrast imaging safe?", "What are diagnostic charges?",
    "Can I access reports online?", "Are diagnostic centers open on weekends?",
    "Does Apollo have an in-house pharmacy?", "Can I order medicines online?",
    "How fast is medicine delivery?", "Is prescription required online?",
    "Does Apollo provide generic medicines?", "How do I track my order?",
    "Are refunds allowed?", "Can I get medication reminders?",
    "Can I consult a pharmacist online?", "Is the pharmacy 24/7?",
    "What services are available for international patients?", "Can Apollo provide a visa invitation letter?",
    "Is airport pickup available?", "How can I estimate my treatment cost?",
    "Are language interpreters available?", "Are international insurance plans accepted?",
    "How do I book a treatment package?", "Can I stay for follow-up care?",
    "How will I receive my post-treatment records?", "Who can I contact for international patient support?",
    "Where is Apollo Hospital located", "Where is Apollo Hospital in Chennai",
    "Apollo Hospital location in Chennai", "Is there an Apollo Hospital in Delhi",
    "Where is Apollo Hospital in Delhi", "Apollo Hospital location in Hyderabad",
    "Where is Apollo Hospital in Hyderabad", "Is Apollo Hospital available in Bengaluru",
    "Where is Apollo Hospital in Bengaluru", "Apollo Hospital location in Kolkata",
    "Where is Apollo Hospital in Kolkata", "Is there an Apollo Hospital in Mumbai",
    "Where is Apollo Hospital in Mumbai", "Apollo Hospital location in Ahmedabad",
    "Where is Apollo Hospital in Ahmedabad",  "Is Apollo Hospital present in Pune",
    "Where is Apollo Hospital in Pune", "Apollo Hospital location in Madurai",
    "Where is Apollo Hospital in Madurai", "Apollo Hospital location in Trichy",
    "Where is Apollo Hospital in Trichy", "Is Apollo Hospital available in Vizag",
    "Where is Apollo Hospital in Vizag", "Apollo Hospital location in Bhubaneswar",
    "Where is Apollo Hospital in Bhubaneswar", "Apollo Hospital location in Indore", "Where is Apollo Hospital in Indore",
    "Is Apollo Hospital available in Lucknow", "Where is Apollo Hospital in Lucknow",
    "Apollo Hospital location in Noida", "Where is Apollo Hospital in Noida",
    "Is Apollo Hospital available in Guwahati", "Where is Apollo Hospital in Guwahati", 
    "Apollo Hospital location in Ranchi", "Where is Apollo Hospital in Ranchi",
    "Apollo Hospital location in Karaikudi", "Where is Apollo Hospital in Karaikudi", 
    "Is Apollo Hospital present in Nellore", "Where is Apollo Hospital in Nellore",
    "Tell me about Apollo Hospital.", "What's the story with this hospital?", "What kind of medical stuff do you do?",
    "When do you guys open?", "What are the timings for the clinic?",
    "How do I talk to a human?", "Is there a support number?", "I need to speak with customer service.",
    "Where is the nearest Apollo?", "Is there an Apollo branch near me?", "Give me the address for the main hospital.",
    "Can I visit my friend in the ward?", "What are the rules for visitors?", "When can I see a patient?",
    "Do you have a chemist inside?", "Is there a lab in the hospital?", "Where can I get a blood test done?",
    "Can I do a video call with a doctor?", "Do you offer virtual visits for foreigners?", "Is remote consultation possible?",
    "Do you take insurance?", "Is my health policy valid here?", "List of covered insurance companies.",
    "How do I use my Star Health insurance?", "Can I get cashless treatment?", "Process for insurance approval.",
    "I need a breakdown of my bill.", "Why is my bill so high?", "Show me the charges for each item.",
    "Can I pay with a credit card?", "Do you accept UPI or Google Pay?", "Is cash okay?",
    "Can I get a refund on my consultation fee?", "I missed my appointment, can I get my money back?",
    "Is there an installment plan for surgery?", "Can I pay in EMIs?", "Do you have financial aid?",
    "I lost my bill, can I get another copy?", "Download my last invoice.", "Send me the receipt on email.",
    "Where are my test results?", "Can I see my reports on my phone?", "Login to see my medical history.",
    "How many days for the biopsy report?", "When will my blood work be ready?", "Are the lab results out yet?",
    "I need my prescription online.", "Where is my digital medicine list?", "Can't find my doctor's note.",
    "Change my phone number in your records.", "Update my home address in the system.",
    "I need my files from 2 years ago.", "Can I get my old discharge summary?", "Requesting archived records.",
    "Is my data private?", "Who can see my medical info?", "Is your database secure?",
    "Can my brother pick up my reports?", "Authorization for someone else to take my results.",
    "I want a second opinion from another doctor.", "Can I show my reports to a different specialist?",
    "I have an emergency!", "Someone is having a heart attack!", "Help, there's an accident!",
    "I need an ambulance right now.", "Send a medic to my location.", "What is the ambulance number?",
    "Where is the ER?", "Take me to casualty.", "Is the emergency room open?",
    "Do I need to call before coming to ER?", "Can I just drive to the emergency gate?",
    "Is ICU available?", "Are there any ventilators free?", "I need a bed in critical care.",
    "Can I stay with my dad in the ICU?", "What are the ICU visiting hours?",
    "How much does an ambulance cost?", "Is emergency care covered by my plan?",
    "Do you have a trauma center?", "Need urgent care for a burn injury.",
    "How do I get admitted?", "I have a surgery scheduled, what's next?", "Admission process for a minor.",
    "What are the room rates?", "How much for a private room?", "Is there a general ward available?",
    "Can I upgrade my room?", "I want a deluxe suite.", "Difference between semi-private and private rooms.",
    "What is included in the bed charges?", "Do you provide food for the patient?", "Is nursing included?",
    "How do I prepare for my operation?", "Should I fast before surgery?", "What time is my surgery?",
    "I want to talk to the anesthesia doctor.", "Is the surgeon available for a chat?",
    "When can I go home after my knee surgery?", "What's the recovery time in hospital?",
    "Can one person stay with the patient overnight?", "Do you provide a bed for the attendant?",
    "How to use the Apollo app?", "Download link for the 24/7 app.", "I'm having trouble logging in.",
    "Start a video consultation.", "How to talk to a doctor on camera?", "My video is not working.",
    "Can I chat with a nurse?", "Is there a live chat for medical advice?",
    "Upload my scans before the call.", "How to attach reports for the doctor to see?",
    "Will the doctor give me a PDF prescription?", "How do I get my medicines after a video call?",
    "Is the online consult covered by my office insurance?", "Cost of a tele-visit.",
    "Track my online medicine order.", "Where is my delivery person?",
    "Can I set a reminder for my pills in the app?", "Medication alert setup.",
    "Book a home sample collection.", "Can someone come home for a blood test?", "Home thyroid test booking.",
    "Do I need to fast for a sugar test?", "Can I drink water before my blood work?",
    "Cost of an MRI scan.", "Price list for diagnostic tests.", "How much for an X-ray?",
    "Is the CT scan safe?", "Any side effects of contrast dye?", "Do I need to sign a consent form?",
    "Are you open for tests on Saturday?", "Can I get an ECG done now?",
    "Where do I download my lab reports?", "Get my urine test result.",
    "Do I need a doctor's slip for a health checkup?", "Can I book a full body checkup directly?",
    "Is the lab certified?", "Are your results accurate?", "How long is the wait for an ultrasound?",
    "I need to buy medicines.", "Do you have this drug in stock?", "Order tablets online.",
    "How long for home delivery of meds?", "Will I get my medicines today?",
    "Can I buy antibiotics without a prescription?", "Do you need a photo of my prescription?",
    "Give me the cheaper generic version.", "Do you have Apollo brand medicines?",
    "Can I return unopened medicine?", "Refund policy for pharmacy.",
    "Remind me when my meds are over.", "Refill my monthly prescription.",
    "Is the pharmacy open at midnight?", "24 hour chemist near me.",
    "I am coming from abroad for treatment.", "Medical tourism services at Apollo.",
    "I need a visa letter for my surgery.", "Help with medical visa documentation.",
    "Can you pick me up from the airport?", "Do you have a guesthouse for foreigners?",
    "How much will the total package cost for a heart surgery?", "Quote for international patients.",
    "I don't speak English, do you have translators?", "Need an Arabic interpreter.",
    "Do you accept international insurance like Bupa or Cigna?", "Foreign insurance clearance.",
    "How to send my reports from my country?", "Can I get a consultation before I fly in?",
    "Who is the coordinator for overseas patients?", "Contact for international desk."
])


# Combine all routes into a single list for the router to use
routes = [faq, appointment]

# Create the semantic router that will automatically classify user queries
# It uses the encoder to compare user input against all route utterances and picks the best match
router = SemanticRouter(encoder=encoder, routes=routes, auto_sync="local")

# This code only runs if you execute this file directly (not when importing it)
if __name__ == "__main__":
    # Test the router with a sample query
    user_input = "is doctor available today?"
    # The router will match this query to the most appropriate route and print its name
    print(router(user_input).name)